version: '3.4'


services:
  geth:
    image: ethereum/client-go:v1.13.0
    ports:
      - '7545:8545'
#      - '8551:8551'
      - 0.0.0.0:${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/tcp
      - 0.0.0.0:${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/udp
    environment:
      - EL_P2P_PORT=${EL_P2P_PORT:-30303}
    entrypoint: /usr/local/bin/geth.sh
    volumes:
      - './data/geth_data:/db'
      - type: bind
        source: ./geth/geth.sh
        target: /usr/local/bin/geth.sh
      - type: bind
        source: ./geth/jwtsecret
        target: /config/jwtsecret
      - type: bind
        source: ./cl_config/genesis.json
        target: /config/genesis.json

  lighthouse:
    image: sigp/lighthouse:v4.4.1
    environment:
      - CL_P2P_PORT=${CL_P2P_PORT:-9000}
      - CL_LOG_LEVEL=${CL_LOG_LEVEL:-info}
    ports:
#      - "5052:5052"
#      - "5054:5054"
      - 0.0.0.0:${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/tcp
      - 0.0.0.0:${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/udp
    command: /usr/local/bin/lighthouse.sh
    volumes:
      - ./data/lighthouse_data:/data
      - type: bind
        source: ./lighthouse/lighthouse.sh
        target: /usr/local/bin/lighthouse.sh
      - type: bind
        source: ./cl_config
        target: /config/testnet
      - type: bind
        source: ./geth/jwtsecret
        target: /config/jwtsecret
